/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDialerRouteImport } from './routes/_app.dialer'
import { Route as AppEmailRouteImport } from './routes/_app.email'
import { Route as AppFollowupsRouteImport } from './routes/_app.followups'
import { Route as AppFutureRouteImport } from './routes/_app.future'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppMeetingsRouteImport } from './routes/_app.meetings'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTelesalesRouteImport } from './routes/_app.telesales'
import { Route as AppWhatsappRouteImport } from './routes/_app.whatsapp'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppCustomersIdRouteImport } from './routes/_app.customers.$id'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInvoicesIdRouteImport } from './routes/_app.invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDialerRoute = AppDialerRouteImport.update({
  id: '/dialer',
  path: '/dialer',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowupsRoute = AppFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AppRoute,
} as any)
const AppFutureRoute = AppFutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTelesalesRoute = AppTelesalesRouteImport.update({
  id: '/telesales',
  path: '/telesales',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/dialer': typeof AppDialerRoute
  '/email': typeof AppEmailRoute
  '/followups': typeof AppFollowupsRoute
  '/future': typeof AppFutureRoute
  '/leads': typeof AppLeadsRoute
  '/meetings': typeof AppMeetingsRoute
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/telesales': typeof AppTelesalesRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/dialer': typeof AppDialerRoute
  '/email': typeof AppEmailRoute
  '/followups': typeof AppFollowupsRoute
  '/future': typeof AppFutureRoute
  '/leads': typeof AppLeadsRoute
  '/meetings': typeof AppMeetingsRoute
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/services': typeof AppServicesRoute
  '/settings': typeof AppSettingsRoute
  '/telesales': typeof AppTelesalesRoute
  '/whatsapp': typeof AppWhatsappRoute
  '/customers/$id': typeof AppCustomersIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/customers': typeof AppCustomersIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dialer': typeof AppDialerRoute
  '/_app/email': typeof AppEmailRoute
  '/_app/followups': typeof AppFollowupsRoute
  '/_app/future': typeof AppFutureRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/meetings': typeof AppMeetingsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/services': typeof AppServicesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/telesales': typeof AppTelesalesRoute
  '/_app/whatsapp': typeof AppWhatsappRoute
  '/_app/customers/$id': typeof AppCustomersIdRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dialer'
    | '/email'
    | '/followups'
    | '/future'
    | '/leads'
    | '/meetings'
    | '/payments'
    | '/reports'
    | '/services'
    | '/settings'
    | '/telesales'
    | '/whatsapp'
    | '/customers/$id'
    | '/invoices/$id'
    | '/customers/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dialer'
    | '/email'
    | '/followups'
    | '/future'
    | '/leads'
    | '/meetings'
    | '/payments'
    | '/reports'
    | '/services'
    | '/settings'
    | '/telesales'
    | '/whatsapp'
    | '/customers/$id'
    | '/invoices/$id'
    | '/customers'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/dialer'
    | '/_app/email'
    | '/_app/followups'
    | '/_app/future'
    | '/_app/leads'
    | '/_app/meetings'
    | '/_app/payments'
    | '/_app/reports'
    | '/_app/services'
    | '/_app/settings'
    | '/_app/telesales'
    | '/_app/whatsapp'
    | '/_app/customers/$id'
    | '/_app/invoices/$id'
    | '/_app/customers/'
    | '/_app/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dialer': {
      id: '/_app/dialer'
      path: '/dialer'
      fullPath: '/dialer'
      preLoaderRoute: typeof AppDialerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email': {
      id: '/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/followups': {
      id: '/_app/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AppFollowupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/future': {
      id: '/_app/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof AppFutureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meetings': {
      id: '/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telesales': {
      id: '/_app/telesales'
      path: '/telesales'
      fullPath: '/telesales'
      preLoaderRoute: typeof AppTelesalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp': {
      id: '/_app/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id': {
      id: '/_app/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDialerRoute: typeof AppDialerRoute
  AppEmailRoute: typeof AppEmailRoute
  AppFollowupsRoute: typeof AppFollowupsRoute
  AppFutureRoute: typeof AppFutureRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTelesalesRoute: typeof AppTelesalesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDialerRoute: AppDialerRoute,
  AppEmailRoute: AppEmailRoute,
  AppFollowupsRoute: AppFollowupsRoute,
  AppFutureRoute: AppFutureRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTelesalesRoute: AppTelesalesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
